name: coral-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - defaults::numpy
  - matplotlib
  - fastapi<0.111.0
  - uvicorn
  - pip
  - mkl
  - intel-openmp
  - mkl-service
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
